### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'RateLimitError'

### ISSUE THREAD

**Issue by bocchi810** [qaqFei/BiliClear#65]
```
Traceback (most recent call last):
  File "C:\Users\Administartor\Desktop\BiliClear-main\biliclear.py", line 19, in <module>
    import gpt
  File "C:\Users\Administartor\Desktop\BiliClear-main\gpt.py", line 8, in <module>
    RateLimitError = openai.RateLimitError
                     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'RateLimitError'
```

**Comment by qaqFei** [comment]
#63 引起的, 已回退
@xiexiaozhua @Felix3322
